#!/bin/sh

# This file is part of nftables-persistent
# (was iptables-persistent)
# Copyright (C) 2019, Adrian Ban <devel@abtelecom.ro>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3
# of the License, or (at your option) any later version.

set -e

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# Source configuration
if [ -f "/etc/default/nftables-persistent" ]; then
    . /etc/default/nftables-persistent
fi

load_rules()
{
    #load IPv4 rules
    if [ ! -f /etc/nftables/rules ]; then
        echo "Warning: skipping (no rules to load)"
    else
        nft -f /etc/nftables/rules
    fi
}

save_rules()
{
    if [ ! "${NFTABLES_SKIP_SAVE}x" = "yesx" ]; then
        touch /etc/nftables/rules
        chmod 0640 /etc/nftables/rules
        nft -n list ruleset > /etc/nftables/rules
    fi
}

flush_rules()
{
    TABLES=$(nft list tables | sed -E -n -e "s/table (.*)/\1/g" -e "s/ +/|/p") #"
    for tableArr in $TABLES
    do
	family=$(echo $tableArr | sed -E -n 's/([a-zA-Z0-9]+)\|.*/\1/p') #'
	table=$(echo $tableArr | sed -E -n 's/[a-zA-Z0-9]+\|([a-zA-Z0-9]+)/\1/p') #'
	nft flush table $family $table
	nft delete table $family $table
    done
}

case "$1" in
start|restart|reload|force-reload)
    load_rules
    ;;
save)
    save_rules
    ;;
stop)
    # Why? because if stop is used, the firewall gets flushed for a variable
    # amount of time during package upgrades, leaving the machine vulnerable
    # It's also not always desirable to flush during purge
    echo "Automatic flushing disabled, use \"flush\" instead of \"stop\""
    ;;
flush)
    flush_rules
    ;;
*)
    echo "Usage: $0 {start|restart|reload|force-reload|save|flush}" >&2
    exit 1
    ;;
esac
